FROM eclipse-mosquitto:2@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
COPY --chown=mosquitto:mosquitto --chmod=0600 infra/mosquitto.conf /mosquitto/config/mosquitto.conf
COPY --chown=mosquitto:mosquitto --chmod=0600 infra/mosquitto-acl.conf /mosquitto/config/acl.conf
