param(
    [string]$ApiUrl = "http://localhost:8080",
    [switch]$ExercisePipeline
)

$ErrorActionPreference = 'Stop'
$health = Invoke-RestMethod "$ApiUrl/api/health"
$failSafe = Invoke-RestMethod "$ApiUrl/api/failsafe"

$failSafe.layers | Select-Object id, status, reason | Format-Table -Wrap -AutoSize
Write-Host "LLM object worker: enabled=$($health.llm_verifier.enabled), running=$($health.llm_verifier.worker), circuit=$($health.llm_verifier.circuit.state)"
Write-Host "LLM security worker: enabled=$($health.security_llm_adviser.enabled), running=$($health.security_llm_adviser.worker), circuit=$($health.security_llm_adviser.circuit.state)"

if (-not $failSafe.critical_path_healthy) {
    throw 'Critical real-time path is degraded. Review the layer table above.'
}
Write-Host 'PASS: live OpenCV, YOLO, ByteTrack, fusion worker, and deterministic rules path are healthy.' -ForegroundColor Green

if (-not $ExercisePipeline) {
    Write-Host 'Read-only verification complete. Use -ExercisePipeline only in an authorised test session.'
    return
}

# This explicit test mode injects synthetic telemetry and one synthetic
# detection to exercise fusion/rules/event dispatch. It never commands a device.
$now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()

$telemetry = @{
    timestamp = $now; latitude = 17.6860; longitude = 83.2180; altitude_m = 40.0; heading_deg = 0.0
    ground_speed_mps = 0.0; battery_percent = 85; link_quality_percent = 99; source = 'backend-verifier'
} | ConvertTo-Json
Invoke-RestMethod "$ApiUrl/api/telemetry" -Method Post -ContentType 'application/json' -Body $telemetry | Out-Null

$batch = @{
    timestamp = $now; source = 'backend-verifier'; frame_width = 1280; frame_height = 720
    detections = @(@{
        track_id = "verify-$now"; class = 'person'; confidence = 0.99
        bbox = @{ x = 600; y = 300; width = 80; height = 160 }
        location = @{ latitude = 17.6860; longitude = 83.2180; approximate = $true; method = 'reported' }
    })
} | ConvertTo-Json -Depth 6
$queued = Invoke-WebRequest "$ApiUrl/api/detections" -Method Post -ContentType 'application/json' -Body $batch -UseBasicParsing
if ($queued.StatusCode -ne 202) { throw "Detection batch was not accepted: $($queued.StatusCode)" }

Start-Sleep -Seconds 2
$snapshot = Invoke-RestMethod "$ApiUrl/api/snapshot"
if (-not ($snapshot.events | Where-Object { $_.track_id -eq "verify-$now" -and $_.event_type -eq 'geofence_entry' })) {
    throw 'No geofence-entry event was generated by the rules layer.'
}
Write-Host 'PASS: synthetic ingestion, fusion, geofence/risk rules, and asynchronous event dispatch are working.' -ForegroundColor Green
