persistence true
persistence_location /mosquitto/data/
autosave_interval 30
autosave_on_changes true
persistent_client_expiration 14d
log_dest stdout

listener 8883 0.0.0.0
protocol mqtt
cafile /run/secrets/tls-ca
certfile /run/secrets/mqtt-server-cert
keyfile /run/secrets/mqtt-server-key
tls_version tlsv1.3
require_certificate true
use_identity_as_username true
allow_anonymous false
acl_file /mosquitto/config/acl.conf
max_queued_messages 10000
max_inflight_messages 100
