user sentinel-api
topic write ground/#
topic write sentinel/v2x/#
topic write sentinel/dead-letter/#

user sentinel-v2x
topic readwrite sentinel/v2x/#

user sentinel-mqtt-health
topic write sentinel/healthcheck
