local   all             all                                     trust
hostssl all             sentinel        0.0.0.0/0               cert clientcert=verify-full map=sentinel_map
hostssl all             sentinel        ::/0                    cert clientcert=verify-full map=sentinel_map
hostnossl all           all             0.0.0.0/0               reject
hostnossl all           all             ::/0                    reject
